### ISSUE TITLE
Google Play Store Improvements

### ISSUE THREAD

**Issue by chnuessli** [chnuessli/defikarte.ch-app#80]
![image](https://user-images.githubusercontent.com/63254403/107851316-54b76c00-6e09-11eb-9053-2ac5bf4fa32f.png)

**Comment by elektrolytmangel** [comment]
If you build the android version, instead of -t apk use -t adb, then you have less issues. But we do not have all the symbol files, and also the second one, will not be solved because of the expo-wrapper application where we do not have control over. In sometime, we will probably eject and use the bare worklfow, then we do not have this issues anymore, I think.

**Comment by chnuessli** [comment]
2/3 fixed with App Bundle instead of APK
